INSERT INTO
  currencies (name, sign, symbol)
VALUES
  ('Russian Ruble', '₽', 'RUB'),
  ('Swedish Krona', 'kr', 'SEK'),
  ('Singapore Dollar', 'S$', 'SGD'),
  ('Thai Baht', '฿', 'THB'),
  ('Turkish Lira', '₺', 'TRY'),
  ('New Taiwan Dollar', 'NT$', 'TWD'),
  ('South African Rand', 'R', 'ZAR'),
  ('United Arab Emirates Dirham', 'د.إ', 'AED'),
  ('Bulgarian Lev', 'лв', 'BGN'),
  ('Croatian Kuna', 'kn', 'HRK'),
  ('Mauritian Rupee', '₨', 'MUR'),
  ('Romanian Leu', 'lei', 'RON'),
  ('Icelandic Króna', 'kr', 'ISK'),
  ('Nigerian Naira', '₦', 'NGN'),
  ('Colombian Peso', '$', 'COP'),
  ('Argentine Peso', '$', 'ARS'),
  ('Peruvian Sol', 'S/.', 'PEN'),
  ('Vietnamese Dong', '₫', 'VND'),
  ('Ukrainian Hryvnia', '₴', 'UAH'),
  ('Bolivian Boliviano', 'Bs.', 'BOB'),
  ('Albanian Lek', 'L', 'ALL'),
  ('Armenian Dram', '֏', 'AMD'),
  ('Azerbaijani Manat', '₼', 'AZN'),
  (
    'Bosnia-Herzegovina Convertible Mark',
    'KM',
    'BAM'
  ),
  ('Bangladeshi Taka', '৳', 'BDT'),
  ('Bahraini Dinar', '.د.ب', 'BHD'),
  ('Bermudan Dollar', '$', 'BMD'),
  ('Belarusian Ruble', 'Br', 'BYN'),
  ('Costa Rican Colón', '₡', 'CRC'),
  ('Cuban Peso', '$', 'CUP'),
  ('Dominican Peso', '$', 'DOP'),
  ('Algerian Dinar', 'د.ج', 'DZD'),
  ('Egyptian Pound', '£', 'EGP'),
  ('Georgian Lari', '₾', 'GEL'),
  ('Ghanaian Cedi', '₵', 'GHS'),
  ('Guatemalan Quetzal', 'Q', 'GTQ'),
  ('Honduran Lempira', 'L', 'HNL'),
  ('Iraqi Dinar', 'ع.د', 'IQD'),
  ('Iranian Rial', '﷼', 'IRR'),
  ('Jamaican Dollar', '$', 'JMD'),
  ('Jordanian Dinar', 'د.ا', 'JOD'),
  ('Kenyan Shilling', 'Sh', 'KES'),
  ('Kyrgystani Som', 'с', 'KGS'),
  ('Cambodian Riel', '៛', 'KHR'),
  ('Kuwaiti Dinar', 'د.ك', 'KWD'),
  ('Kazakhstani Tenge', '₸', 'KZT'),
  ('Lebanese Pound', 'ل.ل', 'LBP'),
  ('Sri Lankan Rupee', 'Rs', 'LKR'),
  ('Moroccan Dirham', 'د.م.', 'MAD'),
  ('Moldovan Leu', 'L', 'MDL'),
  ('Macedonian Denar', 'ден', 'MKD'),
  ('Myanma Kyat', 'Ks', 'MMK'),
  ('Mongolian Tugrik', '₮', 'MNT'),
  ('Namibian Dollar', '$', 'NAD'),
  ('Nicaraguan Córdoba', 'C$', 'NIO'),
  ('Nepalese Rupee', '₨', 'NPR'),
  ('Omani Rial', 'ر.ع.', 'OMR'),
  ('Panamanian Balboa', 'B/.', 'PAB'),
  ('Qatari Rial', 'ر.ق', 'QAR'),
  ('Serbian Dinar', 'дин.', 'RSD'),
  ('Saudi Riyal', 'ر.س', 'SAR'),
  ('South Sudanese Pound', '£', 'SSP'),
  ('Tunisian Dinar', 'د.ت', 'TND'),
  ('Trinidad and Tobago Dollar', '$', 'TTD'),
  ('Ugandan Shilling', 'Sh', 'UGX'),
  ('Uruguayan Peso', '$', 'UYU'),
  ('Uzbekistan Som', 'som', 'UZS'),
  ('Sovereign Bolivar', 'Bs.', 'VES'),
  ('United States Dollar', '$', 'USD'),
  ('Australian Dollar', '$', 'AUD'),
  ('Brazilian Real', 'R$', 'BRL'),
  ('Canadian Dollar', '$', 'CAD'),
  ('Swiss Franc', 'Fr', 'CHF'),
  ('Chilean Peso', '$', 'CLP'),
  ('Chinese Yuan', '¥', 'CNY'),
  ('Czech Koruna', 'Kč', 'CZK'),
  ('Danish Krone', 'kr', 'DKK'),
  ('Euro', '€', 'EUR'),
  ('Pound Sterling', '£', 'GBP'),
  ('Hong Kong Dollar', '$', 'HKD'),
  ('Hungarian Forint', 'Ft', 'HUF'),
  ('Indonesian Rupiah', 'Rp', 'IDR'),
  ('Israeli New Shekel', '₪', 'ILS'),
  ('Indian Rupee', '₹', 'INR'),
  ('Japanese Yen', '¥', 'JPY'),
  ('South Korean Won', '₩', 'KRW'),
  ('Mexican Peso', '$', 'MXN'),
  ('Malaysian Ringgit', 'RM', 'MYR'),
  ('Norwegian Krone', 'kr', 'NOK'),
  ('New Zealand Dollar', '$', 'NZD'),
  ('Philippine Peso', '₱', 'PHP'),
  ('Pakistani Rupee', '₨', 'PKR'),
  ('Polish Złoty', 'zł', 'PLN');