create table "public"."queries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "provider_id" bigint not null,
    "query" text not null,
    "limit" smallint not null
);


alter table "public"."queries" enable row level security;

create table "public"."replies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "reply" text not null
);


alter table "public"."replies" enable row level security;

alter table "public"."posts" drop column "is_comment_generated";

alter table "public"."posts" add column "reply_id" bigint;

CREATE UNIQUE INDEX custom_comments_pkey ON public.replies USING btree (id);

CREATE UNIQUE INDEX queries_pkey ON public.queries USING btree (id);

alter table "public"."queries" add constraint "queries_pkey" PRIMARY KEY using index "queries_pkey";

alter table "public"."replies" add constraint "custom_comments_pkey" PRIMARY KEY using index "custom_comments_pkey";

alter table "public"."posts" add constraint "posts_reply_id_fkey" FOREIGN KEY (reply_id) REFERENCES replies(id) not valid;

alter table "public"."posts" validate constraint "posts_reply_id_fkey";

alter table "public"."queries" add constraint "queries_provider_id_fkey" FOREIGN KEY (provider_id) REFERENCES providers(id) not valid;

alter table "public"."queries" validate constraint "queries_provider_id_fkey";


