create table "public"."followers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "provider_id" bigint,
    "username" text not null,
    "is_following" boolean not null default false,
    "is_sent" boolean not null default false
);


alter table "public"."followers" enable row level security;

CREATE UNIQUE INDEX followers_pkey ON public.followers USING btree (id);

alter table "public"."followers" add constraint "followers_pkey" PRIMARY KEY using index "followers_pkey";

alter table "public"."followers" add constraint "followers_provider_id_fkey" FOREIGN KEY (provider_id) REFERENCES providers(id) not valid;

alter table "public"."followers" validate constraint "followers_provider_id_fkey";


