drop policy "Enable read access for all users" on "public"."project_categories";

drop policy "Enable read access for all users" on "public"."rfp_categories";

alter table "public"."project_categories" drop constraint "project_categories_category_id_fkey";

alter table "public"."project_categories" drop constraint "project_categories_project_id_fkey";

alter table "public"."rfp_categories" drop constraint "rfp_categories_category__fkey";

alter table "public"."rfp_categories" drop constraint "rfp_categories_rfp_id_fkey";

alter table "public"."project_categories" drop constraint "project_categories_pkey";

alter table "public"."rfp_categories" drop constraint "rfp_categories_pkey";

drop index if exists "public"."project_categories_pkey";

drop index if exists "public"."rfp_categories_pkey";

drop table "public"."project_categories";

drop table "public"."rfp_categories";

create table "public"."project_use_cases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "use_case_id" bigint not null,
    "project_id" bigint not null
);


alter table "public"."project_use_cases" enable row level security;

create table "public"."rfp_use_cases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "rfp_id" bigint not null,
    "use_case_id" bigint not null
);


alter table "public"."rfp_use_cases" enable row level security;

CREATE UNIQUE INDEX project_use_cases_pkey ON public.project_use_cases USING btree (id);

CREATE UNIQUE INDEX rfp_categories_pkey ON public.rfp_use_cases USING btree (id);

alter table "public"."project_use_cases" add constraint "project_use_cases_pkey" PRIMARY KEY using index "project_use_cases_pkey";

alter table "public"."rfp_use_cases" add constraint "rfp_categories_pkey" PRIMARY KEY using index "rfp_categories_pkey";

alter table "public"."project_use_cases" add constraint "project_use_cases_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) not valid;

alter table "public"."project_use_cases" validate constraint "project_use_cases_project_id_fkey";

alter table "public"."project_use_cases" add constraint "project_use_cases_use_case_id_fkey" FOREIGN KEY (use_case_id) REFERENCES categories(id) not valid;

alter table "public"."project_use_cases" validate constraint "project_use_cases_use_case_id_fkey";

alter table "public"."rfp_use_cases" add constraint "rfp_use_cases_rfp_id_fkey" FOREIGN KEY (rfp_id) REFERENCES rfps(id) not valid;

alter table "public"."rfp_use_cases" validate constraint "rfp_use_cases_rfp_id_fkey";

alter table "public"."rfp_use_cases" add constraint "rfp_use_cases_use_case_id_fkey" FOREIGN KEY (use_case_id) REFERENCES use_cases(id) not valid;

alter table "public"."rfp_use_cases" validate constraint "rfp_use_cases_use_case_id_fkey";

create policy "Enable read access for all users"
on "public"."project_use_cases"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."rfp_use_cases"
as permissive
for select
to public
using (true);



