create table "public"."blockchains" (
    "id" bigint generated by default as identity not null,
    "blockchain" character varying,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."blockchains" enable row level security;

create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "category" character varying not null
);


alter table "public"."categories" enable row level security;

create table "public"."fiats" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" character varying not null,
    "sign" character varying not null,
    "symbol" character varying not null
);


alter table "public"."fiats" enable row level security;

create table "public"."grant_blockchains" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "grant_id" bigint not null,
    "blockchain_id" bigint not null
);


alter table "public"."grant_blockchains" enable row level security;

create table "public"."grant_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "category_id" bigint not null,
    "grant_id" bigint not null
);


alter table "public"."grant_categories" enable row level security;

create table "public"."grant_use_cases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "use_case_id" bigint not null,
    "grant_id" bigint not null
);


alter table "public"."grant_use_cases" enable row level security;

create table "public"."grants" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "grant" character varying not null,
    "description" text,
    "active" boolean not null,
    "url_application" text not null,
    "url_info" text,
    "content" text not null,
    "slug" character varying,
    "funding_minimum" integer,
    "funding_maximum" integer,
    "funding_minimum_currency" bigint,
    "funding_maximum_currency" bigint,
    "twitter" text,
    "github" text,
    "discord" text,
    "telegram" text,
    "website" text,
    "logo" uuid
);


alter table "public"."grants" enable row level security;

create table "public"."use_cases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "use_case" character varying not null
);


alter table "public"."use_cases" enable row level security;

CREATE UNIQUE INDEX blockchains_blockchain_key ON public.blockchains USING btree (blockchain);

CREATE UNIQUE INDEX blockchains_pkey ON public.blockchains USING btree (id);

CREATE UNIQUE INDEX categories_category_key ON public.categories USING btree (category);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX fiats_pkey ON public.fiats USING btree (id);

CREATE UNIQUE INDEX grant_blockchains_pkey ON public.grant_blockchains USING btree (id);

CREATE UNIQUE INDEX grant_categories_pkey ON public.grant_categories USING btree (id);

CREATE UNIQUE INDEX grant_use_cases_pkey ON public.grant_use_cases USING btree (id);

CREATE UNIQUE INDEX grants_pkey ON public.grants USING btree (id);

CREATE UNIQUE INDEX use_cases_pkey ON public.use_cases USING btree (id);

CREATE UNIQUE INDEX use_cases_use_case_key ON public.use_cases USING btree (use_case);

alter table "public"."blockchains" add constraint "blockchains_pkey" PRIMARY KEY using index "blockchains_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."fiats" add constraint "fiats_pkey" PRIMARY KEY using index "fiats_pkey";

alter table "public"."grant_blockchains" add constraint "grant_blockchains_pkey" PRIMARY KEY using index "grant_blockchains_pkey";

alter table "public"."grant_categories" add constraint "grant_categories_pkey" PRIMARY KEY using index "grant_categories_pkey";

alter table "public"."grant_use_cases" add constraint "grant_use_cases_pkey" PRIMARY KEY using index "grant_use_cases_pkey";

alter table "public"."grants" add constraint "grants_pkey" PRIMARY KEY using index "grants_pkey";

alter table "public"."use_cases" add constraint "use_cases_pkey" PRIMARY KEY using index "use_cases_pkey";

alter table "public"."blockchains" add constraint "blockchains_blockchain_key" UNIQUE using index "blockchains_blockchain_key";

alter table "public"."categories" add constraint "categories_category_key" UNIQUE using index "categories_category_key";

alter table "public"."grant_blockchains" add constraint "grant_blockchains_blockchain_id_fkey" FOREIGN KEY (blockchain_id) REFERENCES blockchains(id) not valid;

alter table "public"."grant_blockchains" validate constraint "grant_blockchains_blockchain_id_fkey";

alter table "public"."grant_blockchains" add constraint "grant_blockchains_grant_id_fkey" FOREIGN KEY (grant_id) REFERENCES grants(id) not valid;

alter table "public"."grant_blockchains" validate constraint "grant_blockchains_grant_id_fkey";

alter table "public"."grant_categories" add constraint "grant_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."grant_categories" validate constraint "grant_categories_category_id_fkey";

alter table "public"."grant_categories" add constraint "grant_categories_grant_id_fkey" FOREIGN KEY (grant_id) REFERENCES grants(id) not valid;

alter table "public"."grant_categories" validate constraint "grant_categories_grant_id_fkey";

alter table "public"."grant_use_cases" add constraint "grant_use_cases_grant_id_fkey" FOREIGN KEY (grant_id) REFERENCES grants(id) not valid;

alter table "public"."grant_use_cases" validate constraint "grant_use_cases_grant_id_fkey";

alter table "public"."grant_use_cases" add constraint "grant_use_cases_use_case_id_fkey" FOREIGN KEY (use_case_id) REFERENCES use_cases(id) not valid;

alter table "public"."grant_use_cases" validate constraint "grant_use_cases_use_case_id_fkey";

alter table "public"."grants" add constraint "grants_funding_maximum_currency_fkey" FOREIGN KEY (funding_maximum_currency) REFERENCES fiats(id) not valid;

alter table "public"."grants" validate constraint "grants_funding_maximum_currency_fkey";

alter table "public"."grants" add constraint "grants_funding_minimum_currency_fkey" FOREIGN KEY (funding_minimum_currency) REFERENCES fiats(id) not valid;

alter table "public"."grants" validate constraint "grants_funding_minimum_currency_fkey";

alter table "public"."grants" add constraint "grants_logo_fkey" FOREIGN KEY (logo) REFERENCES storage.objects(id) not valid;

alter table "public"."grants" validate constraint "grants_logo_fkey";

alter table "public"."use_cases" add constraint "use_cases_use_case_key" UNIQUE using index "use_cases_use_case_key";


