create table "public"."grant_rfps" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "grant_id" bigint,
    "rfp_id" bigint
);


alter table "public"."grant_rfps" enable row level security;

create table "public"."rfp_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "rfp_id" bigint,
    "category_" bigint
);


alter table "public"."rfp_categories" enable row level security;

create table "public"."rfp_priorities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text
);


alter table "public"."rfp_priorities" enable row level security;

create table "public"."rfp_statuses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "status" text
);


alter table "public"."rfp_statuses" enable row level security;

create table "public"."rfps" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null,
    "description" text not null,
    "funding_minimum" bigint,
    "funding_minimum_currency" bigint,
    "funding_maximum" bigint,
    "funding_maximum_currency" bigint,
    "deadline_at" timestamp with time zone,
    "status_id" bigint,
    "priority_id" bigint
);


alter table "public"."rfps" enable row level security;

CREATE UNIQUE INDEX grant_rfps_pkey ON public.grant_rfps USING btree (id);

CREATE UNIQUE INDEX rfp_categories_pkey ON public.rfp_categories USING btree (id);

CREATE UNIQUE INDEX rfp_priorities_pkey ON public.rfp_priorities USING btree (id);

CREATE UNIQUE INDEX rfps_pkey ON public.rfps USING btree (id);

CREATE UNIQUE INDEX statuses_pkey ON public.rfp_statuses USING btree (id);

alter table "public"."grant_rfps" add constraint "grant_rfps_pkey" PRIMARY KEY using index "grant_rfps_pkey";

alter table "public"."rfp_categories" add constraint "rfp_categories_pkey" PRIMARY KEY using index "rfp_categories_pkey";

alter table "public"."rfp_priorities" add constraint "rfp_priorities_pkey" PRIMARY KEY using index "rfp_priorities_pkey";

alter table "public"."rfp_statuses" add constraint "statuses_pkey" PRIMARY KEY using index "statuses_pkey";

alter table "public"."rfps" add constraint "rfps_pkey" PRIMARY KEY using index "rfps_pkey";

alter table "public"."grant_rfps" add constraint "grant_rfps_grant_id_fkey" FOREIGN KEY (grant_id) REFERENCES grants(id) not valid;

alter table "public"."grant_rfps" validate constraint "grant_rfps_grant_id_fkey";

alter table "public"."grant_rfps" add constraint "grant_rfps_rfp_id_fkey" FOREIGN KEY (rfp_id) REFERENCES rfps(id) not valid;

alter table "public"."grant_rfps" validate constraint "grant_rfps_rfp_id_fkey";

alter table "public"."rfp_categories" add constraint "rfp_categories_category__fkey" FOREIGN KEY (category_) REFERENCES categories(id) not valid;

alter table "public"."rfp_categories" validate constraint "rfp_categories_category__fkey";

alter table "public"."rfp_categories" add constraint "rfp_categories_rfp_id_fkey" FOREIGN KEY (rfp_id) REFERENCES rfps(id) not valid;

alter table "public"."rfp_categories" validate constraint "rfp_categories_rfp_id_fkey";

alter table "public"."rfps" add constraint "rfps_funding_maximum_currency_fkey" FOREIGN KEY (funding_maximum_currency) REFERENCES fiats(id) not valid;

alter table "public"."rfps" validate constraint "rfps_funding_maximum_currency_fkey";

alter table "public"."rfps" add constraint "rfps_funding_minimum_currency_fkey" FOREIGN KEY (funding_minimum_currency) REFERENCES fiats(id) not valid;

alter table "public"."rfps" validate constraint "rfps_funding_minimum_currency_fkey";

alter table "public"."rfps" add constraint "rfps_priority_id_fkey" FOREIGN KEY (priority_id) REFERENCES rfp_priorities(id) not valid;

alter table "public"."rfps" validate constraint "rfps_priority_id_fkey";

alter table "public"."rfps" add constraint "rfps_status_id_fkey" FOREIGN KEY (status_id) REFERENCES rfp_statuses(id) not valid;

alter table "public"."rfps" validate constraint "rfps_status_id_fkey";

create policy "Enable read access for all users"
on "public"."grant_project_payments"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."grant_projects"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."grant_rfps"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_categories"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."projects"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."rfp_categories"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."rfp_priorities"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."rfp_statuses"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."rfps"
as permissive
for select
to public
using (true);



