create table "public"."grant_project_payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "grant_id" bigint not null,
    "project_id" bigint not null,
    "amount_paid_value" bigint not null,
    "amount_paid_fiat" bigint not null,
    "transaction_reference" text not null
);


alter table "public"."grant_project_payments" enable row level security;

create table "public"."grant_projects" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "last_updated_at" timestamp with time zone default now(),
    "grant_id" bigint not null,
    "project_id" bigint not null,
    "amount_requested_value" bigint,
    "amount_requested_curency" bigint,
    "start_date" date,
    "end_date" date
);


alter table "public"."grant_projects" enable row level security;

create table "public"."project_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "category_id" bigint not null,
    "project_id" bigint not null
);


alter table "public"."project_categories" enable row level security;

create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "last_updated_at" timestamp with time zone default now(),
    "name" text not null,
    "logo" text,
    "url" text
);


alter table "public"."projects" enable row level security;

CREATE UNIQUE INDEX grant_project_payments_pkey ON public.grant_project_payments USING btree (id);

CREATE UNIQUE INDEX grant_projects_pkey ON public.grant_projects USING btree (id);

CREATE UNIQUE INDEX project_categories_pkey ON public.project_categories USING btree (category_id, project_id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

alter table "public"."grant_project_payments" add constraint "grant_project_payments_pkey" PRIMARY KEY using index "grant_project_payments_pkey";

alter table "public"."grant_projects" add constraint "grant_projects_pkey" PRIMARY KEY using index "grant_projects_pkey";

alter table "public"."project_categories" add constraint "project_categories_pkey" PRIMARY KEY using index "project_categories_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."grant_project_payments" add constraint "grant_project_payments_amount_paid_fiat_fkey" FOREIGN KEY (amount_paid_fiat) REFERENCES fiats(id) not valid;

alter table "public"."grant_project_payments" validate constraint "grant_project_payments_amount_paid_fiat_fkey";

alter table "public"."grant_project_payments" add constraint "grant_project_payments_grant_id_fkey" FOREIGN KEY (grant_id) REFERENCES grants(id) not valid;

alter table "public"."grant_project_payments" validate constraint "grant_project_payments_grant_id_fkey";

alter table "public"."grant_project_payments" add constraint "grant_project_payments_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) not valid;

alter table "public"."grant_project_payments" validate constraint "grant_project_payments_project_id_fkey";

alter table "public"."grant_projects" add constraint "grant_projects_amount_requested_curency_fkey" FOREIGN KEY (amount_requested_curency) REFERENCES fiats(id) not valid;

alter table "public"."grant_projects" validate constraint "grant_projects_amount_requested_curency_fkey";

alter table "public"."grant_projects" add constraint "grant_projects_grant_id_fkey" FOREIGN KEY (grant_id) REFERENCES grants(id) not valid;

alter table "public"."grant_projects" validate constraint "grant_projects_grant_id_fkey";

alter table "public"."grant_projects" add constraint "grant_projects_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) not valid;

alter table "public"."grant_projects" validate constraint "grant_projects_project_id_fkey";

alter table "public"."project_categories" add constraint "project_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."project_categories" validate constraint "project_categories_category_id_fkey";

alter table "public"."project_categories" add constraint "project_categories_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) not valid;

alter table "public"."project_categories" validate constraint "project_categories_project_id_fkey";


