create table "public"."authors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "author_id" character varying not null,
    "username" character varying not null,
    "is_following" boolean default false,
    "provider_id" bigint not null
);


alter table "public"."authors" enable row level security;

create table "public"."providers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" character varying not null
);



